version: '3.8'
services:
  mongo:
    image: mongo.latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      - MONGODB_DATABASE_NAME: ${MONGO_DATABASE_NAME}
    env_file:
      - ./.env
    volumes:
      - mongo: /data/db
    ports:
      -'6000:27017'

  redis:
    image: radis.latest
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  mongo:
  redis: